language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jurisbandenieks/react-test -f ./client/Dockerfile.dev ./client

# script:
#   - docker run -e CI=true jurisbandenieks/react-test npm test

after_success:
  - docker build -t jurisbandenieks/multi-client ./client
  - docker build -t jurisbandenieks/multi-nginx ./nginx
  - docker build -t jurisbandenieks/multi-server ./server
  - docker build -t jurisbandenieks/multi-worker ./worker

  # Log in docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push jurisbandenieks/multi-client
  - docker push jurisbandenieks/multi-nginx
  - docker push jurisbandenieks/multi-server
  - docker push jurisbandenieks/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-south-1"
  app: "complex"
  env: "Complex-env"
  bucket_name: "elasticbeanstalk-eu-south-1-949370492564"
  bucket_path: "complex"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
